FROM node:lts-alpine3.22 as builder
COPY . .
RUN npm install
RUN npm run build

FROM node:lts-alpine3.22 as runner
WORKDIR /app
ENV NODE_ENV=production

#copy application files
COPY ./.env ./
COPY ./package.json ./
COPY --from=builder /dist ./dist
RUN npm install

CMD npm dev