version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN_NEXT_FE}
    depends_on:
      - backend
    networks:
      - taskmanager-network
      - nginx_proxy_manager_default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN_NEXT_BE}
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongodb
      - redis
    networks:
      - taskmanager-network
      - nginx_proxy_manager_default

  mongodb:
    image: mongo:6
    container_name: taskmanager-mongodb
    restart: unless-stopped
    # Uncomment the next 2 lines temporarily for MongoDB Compass access
    ports:
      - "2109:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - taskmanager-network
    command: mongod --auth --bind_ip_all

  redis:
    image: redis:7-alpine
    container_name: taskmanager-redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - taskmanager-network
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}

networks:
  taskmanager-network:
    driver: bridge
  nginx_proxy_manager_default:  # <-- ADD THIS
    external: true

volumes:
  mongodb-data:
  redis-data:
